name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            shortcut: cs9
            container-name: stream9
          - name: centos-stream-10
            shortcut: cs10
            container-name: stream10

    name: ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/centos/centos:${{ matrix.container-name }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v5

    - name: Install dependencies
      run: dnf install -y rpmdevtools

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Upload artifacts
      uses: ovirt/upload-rpms-action@main
      with:
        directory: ${{ env.ARTIFACTS_DIR }}
